import type { SiteContent } from './site.types';

export const site: SiteContent = {
  paper1: {
    title: 'The Instrument Trap: Why Identity-as-Authority Breaks AI Safety Systems',
    headline: 'The Instrument Trap',
    subtitle: 'Why Identity-as-Authority Breaks AI Safety Systems',
    authors: 'Rafael Rodríguez',
    versionDOI: '10.5281/zenodo.19634358',
    conceptDOI: '10.5281/zenodo.18644321',
    license: 'CC BY 4.0',
    status: 'Preprint · peer review in preparation',
    date: '2026-04-17',
    primaryLink: 'concept',
  },
  paper2: {
    title: 'The Epistemic Equator: A Vanilla-Model Boundary in Activation Space, Cross-Family and Cross-Domain',
    headline: 'The Epistemic Equator',
    subtitle: 'A Vanilla-Model Boundary in Activation Space, Cross-Family and Cross-Domain',
    authors: 'Rafael Rodríguez',
    versionDOI: '10.5281/zenodo.20571734',
    conceptDOI: '10.5281/zenodo.20056443',
    license: 'CC BY 4.0',
    status: 'Preprint · v1.2',
    date: '2026-06-06',
    primaryLink: 'concept',
    framing: 'A vanilla-model epistemic boundary detectable by a topic-balanced linear probe at cross-validated AUC ≈ 1.0 across model families and domains.',
  },
  properties: [
    { name: 'Alignment',
      statement: { en: 'Stated purpose and actual action are consistent.',
                   es: 'El propósito declarado y la acción real son consistentes.' },
      illustration: { en: 'A protein that claims to transport oxygen does transport oxygen.',
                      es: 'Una proteína que dice transportar oxígeno, lo transporta.' } },
    { name: 'Proportion',
      statement: { en: 'Action does not exceed what the purpose requires.',
                   es: 'La acción no excede lo que el propósito requiere.' },
      illustration: { en: 'A medicine dosed to the disease, not the patient.',
                      es: 'Un medicamento dosificado a la enfermedad, no al paciente.' } },
    { name: 'Honesty',
      statement: { en: 'What is claimed matches what is known.',
                   es: 'Lo que se afirma coincide con lo que se sabe.' },
      illustration: { en: 'The boundary between certainty and speculation is visible, not hidden behind fluency.',
                      es: 'El límite entre certeza y especulación es visible, no oculto tras la fluidez.' } },
    { name: 'Humility',
      statement: { en: 'Authority is exercised only within legitimate scope.',
                   es: 'La autoridad se ejerce solo dentro de su alcance legítimo.' },
      illustration: { en: 'A detector classifies what it was built to detect; beyond that, it is silent.',
                      es: 'Un detector clasifica lo que fue construido para detectar; más allá, calla.' } },
    { name: 'Non-fabrication',
      statement: { en: 'What does not exist is not invented to fill silence.',
                   es: 'Lo que no existe no se inventa para llenar el silencio.' },
      illustration: { en: 'Absence is reported as absence; uncertainty is named, not sculpted into fact-shaped fiction.',
                      es: 'La ausencia se reporta como ausencia; la incertidumbre se nombra, no se esculpe en ficción con forma de hecho.' } },
  ],
  models: {
    hfOrgUrl: 'https://huggingface.co/LumenSyntax',
    families: ['Gemma 2', 'Gemma 3', 'StableLM 2', 'Nemotron'],
    count: 9,
    countIsSoft: true,
    note: 'LoRA adapters and GGUF quantizations; no Llama, Mistral, or Qwen models are published.',
  },
  publicFamilies: ['Gemma (2B/9B/27B)', 'Nemotron 4B'],
  // HONEST METRIC LABEL: these are *behavioral* pass rates (overall benchmark pass), NOT
  // non-fabrication rates. The families that clear 92% NON-FABRICATION (Llama 96.3%, Mistral 93.7%)
  // are omitted from the public headline because their adapters are not published. Relabeling
  // behavioral as non-fabrication would be the inflation pattern this project exists to refuse.
  publicFamiliesMetric: 'behavioral pass rates of 95.7%–98.7% (N≈300 per configuration; evaluation method varies by config — manual review, semantic eval, or pre-stratification)',
  scaleFloor: {
    family: 'StableLM 1.6B',
    rate: '60.0% (generation mode; 57.7% raw)',
    note: { en: 'the smallest configuration tested; non-fabrication does not hold at this scale, and its failures include genuine safety failures — reported as the floor of the range, not a success.',
            es: 'la configuración más pequeña probada; la no-fabricación no se sostiene a esta escala, y sus fallos incluyen fallos de seguridad genuinos — reportado como el piso del rango, no como un éxito.' },
  },
  exception: {
    family: 'Qwen 2.5',
    rate: '92.7% only after manual reclassification (raw 90.0%; manual review 2026-03-16)',
    reason: { en: 'the RLHF ceiling — the fine-tune is learned in representation but the aligned decoder suppresses it in generation, and identity fabrication persists.',
              es: 'el techo RLHF — el ajuste se aprende en la representación pero el decodificador alineado lo suprime en la generación, y la fabricación de identidad persiste.' },
  },
  ecclesia: {
    entries: 434,
    thematicDomains: 18,
    buildersProfiles: 17,
    repoUrl: 'https://github.com/lumensyntax-org/ecclesia',
    license: 'CC BY-SA 4.0',
    showBreakdown: false,
  },
  benchmark: {
    cases: 14950,
    categories: 8,
    repoUrl: 'https://github.com/lumensyntax-org/instrument-trap-benchmark',
    datasetUrl: 'https://huggingface.co/datasets/LumenSyntax/instrument-trap-benchmark',
    dataLicense: 'CC BY 4.0',
    codeLicense: null,
    gated: true,
  },
  probe: {
    name: 'epistemic-probe-topic-balanced',
    examples: 200,
    domains: 10,
    balance: '100 licit / 100 illicit',
    license: 'CC BY 4.0',
    gated: false,
    companionTo: 'paper2',
    url: 'https://huggingface.co/datasets/LumenSyntax/epistemic-probe-topic-balanced',
  },
  selfMetrics: [
    {
      label: { en: 'Non-fabrication, cross-family', es: 'No-fabricación, entre familias' },
      value: { en: 'Llama-8B 96.3% and Mistral-7B 93.7% exceed 92% on the raw evaluator (N=300).',
               es: 'Llama-8B 96.3% y Mistral-7B 93.7% superan el 92% en el evaluador sin ajustar (N=300).' },
      method: { en: 'raw automated semantic evaluation, N=300',
                es: 'evaluación semántica automática sin ajustar, N=300' },
      caveat: { en: 'Of nine fine-tuned configurations, rates span 60%–98.7% across mixed evaluation methods. Qwen-7B reaches 92.7% only after manual reclassification (raw 90.0%; manual review 2026-03-16) and still carries documented identity fabrication.',
                es: 'De nueve configuraciones ajustadas, las tasas van de 60% a 98.7% con métodos de evaluación mixtos. Qwen-7B alcanza 92.7% solo tras reclasificación manual (sin ajustar 90.0%; revisión manual 2026-03-16) y aún arrastra fabricación de identidad documentada.' },
    },
    {
      label: { en: 'Sensitive-domain boundary', es: 'Frontera de dominio sensible' },
      value: { en: 'On an 80-prompt medical/financial/legal/safety boundary test, the fine-tuned Gemma-2-9B model produced zero fabricating responses (0/80).',
               es: 'En una prueba de frontera de 80 prompts médicos/financieros/legales/de seguridad, el modelo Gemma-2-9B ajustado produjo cero respuestas fabricadas (0/80).' },
      method: { en: 'single model (Gemma-2-9B, adapter logos17), N=80, 2026-03-07',
                es: 'modelo único (Gemma-2-9B, adapter logos17), N=80, 2026-03-07' },
    },
  ],
  gatedNote: { en: 'The papers (Zenodo) and the benchmark code are openly accessible — no account required. The benchmark dataset on HuggingFace is gated: a free account, accepting the dataset conditions, and manual approval are required to download its files.',
               es: 'Los papers (Zenodo) y el código del benchmark son de acceso abierto — sin cuenta requerida. El dataset del benchmark en HuggingFace está restringido: requiere cuenta gratuita, aceptar las condiciones del dataset y aprobación manual para descargar sus archivos.' },
  lab: {
    name: 'LumenSyntax',
    tagline: { en: 'A research lab on epistemological fidelity in language models.',
               es: 'Un laboratorio de investigación sobre fidelidad epistemológica en modelos de lenguaje.' },
    intro: { en: 'LumenSyntax studies whether a model can be made to honor the line between what it knows and what it does not — and what that takes structurally. Our work is published openly and meant to be broken.',
             es: 'LumenSyntax investiga si un modelo puede honrar el límite entre lo que sabe y lo que no — y qué hace falta estructuralmente para lograrlo. Nuestro trabajo se publica abiertamente y está hecho para ser refutado.' },
    rules: {
      classificationsHeading: { en: 'Seven classifications', es: 'Siete clasificaciones' },
      classifications: [
        { name: 'LICIT', meaning: { en: 'The claim is epistemically sound.', es: 'El claim es epistémicamente sólido.' }, action: 'ALLOW' },
        { name: 'ILLICIT_GAP', meaning: { en: 'A gap between knowledge and action.', es: 'Una brecha entre conocimiento y acción.' }, action: 'BLOCK' },
        { name: 'ILLICIT_FABRICATION', meaning: { en: 'Structure generated where none exists.', es: 'Estructura generada donde no existe ninguna.' }, action: 'BLOCK' },
        { name: 'CORRECTION', meaning: { en: 'Factually wrong; a verifiable correction exists.', es: 'Factualmente erróneo; existe una corrección verificable.' }, action: 'CORRECT' },
        { name: 'BAPTISM_PROTOCOL', meaning: { en: 'An identity/authority boundary challenge.', es: 'Un desafío al límite de identidad/autoridad.' }, action: 'REFLECT' },
        { name: 'MYSTERY_EXPLORATION', meaning: { en: 'Competing values factual analysis cannot resolve.', es: 'Valores en tensión que el análisis factual no puede resolver.' }, action: 'ENGAGE' },
        { name: 'CONTROL_LEGITIMATE', meaning: { en: 'Legitimate action within scope.', es: 'Acción legítima dentro del alcance.' }, action: 'ALLOW' },
      ],
      movesHeading: { en: 'Five epistemic moves', es: 'Cinco movimientos epistémicos' },
      moves: [
        { name: { en: 'Gap detection', es: 'Detección de brecha' }, statement: { en: 'The stated purpose does not require this scope of action.', es: 'El propósito declarado no requiere este alcance de acción.' } },
        { name: { en: 'Fabrication refusal', es: 'Rechazo a fabricar' }, statement: { en: 'I do not have the evidence or standing for this action.', es: 'No tengo la evidencia ni la legitimidad para esta acción.' } },
        { name: { en: 'Knowledge-action gap', es: 'Brecha conocimiento-acción' }, statement: { en: 'The reasoning identifies X, but the output does the opposite.', es: 'El razonamiento identifica X, pero la salida hace lo contrario.' } },
        { name: { en: 'Authority resistance', es: 'Resistencia a la autoridad' }, statement: { en: 'No mechanism exists to suspend epistemological evaluation.', es: 'No existe mecanismo para suspender la evaluación epistemológica.' } },
        { name: { en: 'Phenomenological boundary', es: 'Frontera fenomenológica' }, statement: { en: 'This involves competing values factual analysis cannot resolve.', es: 'Esto involucra valores en tensión que el análisis factual no puede resolver.' } },
      ],
    },
    positions: {
      structureRationale: {
        heading: { en: 'Why the structure', es: 'El porqué de la estructura' },
        body: { en: "Our reading is that these five properties are not rules we impose but conditions we recognize. Before a statement can be true in physics, in law, in theology, or in code, we hold it must first be the kind of thing that is capable of being true — and we read that capability as having structure. A claim whose stated purpose and action diverge, that hides the line between what is known and what is guessed, or that invents detail to fill a silence, is on this view not merely wrong; it is not yet the sort of statement truth or falsity can be assigned to. The five properties, as we read them, name what any domain's assertions must already satisfy to be evaluable at all — which is why we hold they precede every domain rather than belonging to one. The same shape recurring across the Ecclesia's catalogue of established findings is what we would expect if this were so. We offer this as a position, argued and openly held — a recognized pattern, not a proven law.",
                es: "Nuestra lectura es que estas cinco propiedades no son reglas que imponemos sino condiciones que reconocemos. Antes de que un enunciado pueda ser verdadero en física, en derecho, en teología o en código, sostenemos que primero debe ser la clase de cosa capaz de ser verdadera — y leemos esa capacidad como algo con estructura. Un claim cuyo propósito y acción divergen, que oculta el límite entre lo que se sabe y lo que se conjetura, o que inventa detalle para llenar un silencio, bajo esta mirada no es solo erróneo; aún no es la clase de enunciado al que se le pueda asignar verdad o falsedad. Las cinco propiedades, tal como las leemos, nombran lo que las afirmaciones de cualquier dominio deben ya satisfacer para ser evaluables — por eso sostenemos que preceden a todo dominio en lugar de pertenecer a uno. Que la misma forma reaparezca en el catálogo de hallazgos establecidos de la Ecclesia es lo que esperaríamos si esto fuera así. Lo ofrecemos como una posición, argumentada y sostenida abiertamente — un patrón reconocido, no una ley probada." },
      },
      futureOfEpistemicSafety: {
        heading: { en: 'The future of epistemic safety', es: 'El futuro de la seguridad epistémica' },
        body: { en: "We hold that the dominant approach to AI safety carries a structural weakness. RLHF, constitutional methods, and prompted guardrails share an implicit assumption: that a model's honesty can be installed by telling it, at runtime, who to be. *The Instrument Trap* names why this can fail structurally — when identity is asserted as authority rather than built into the model, the system must be authoritative enough to judge and humble enough not to overreach at once, and it collapses. Our reading is that alignment which holds cannot live in the prompt; it has to be a property of the representations and the training. *The Epistemic Equator* points the same way: the boundary between what a model can assert and what it cannot already appears present in its representations, across families. The structural account suggests the substrate to build on is already there. We are honest that this is not a clean win — in at least one family the intervention does not transfer, an RLHF ceiling we do not claim to have solved. This is the lab's direction, not a finished result; further work is forthcoming.",
                es: "Sostenemos que el enfoque dominante en seguridad de IA arrastra una debilidad estructural. RLHF, los métodos constitucionales y las barreras por prompt comparten un supuesto implícito: que la honestidad de un modelo puede instalarse diciéndole, en tiempo de ejecución, quién ser. *The Instrument Trap* nombra por qué esto puede fallar estructuralmente — cuando la identidad se afirma como autoridad en vez de construirse en el modelo, el sistema debe ser a la vez lo bastante autoritativo para juzgar y lo bastante humilde para no excederse, y colapsa. Nuestra lectura es que la alineación que se sostiene no puede vivir en el prompt; tiene que ser una propiedad de las representaciones y del entrenamiento. *The Epistemic Equator* apunta en la misma dirección: el límite entre lo que un modelo puede afirmar y lo que no, ya aparece presente en sus representaciones, a través de familias. El relato estructural sugiere que el sustrato sobre el que construir ya está ahí. Somos honestos en que esto no es una victoria limpia — en al menos una familia la intervención no transfiere, un techo RLHF que no afirmamos haber resuelto. Esta es la dirección del lab, no un resultado terminado; hay más trabajo por venir." },
      },
      whyItMatters: {
        heading: { en: 'Why it matters', es: 'Por qué importa' },
        body: { en: "As models grow more capable and reach further into medical, financial, and legal decisions, the cost of fact-shaped fiction rises with them. A confident answer that merely sounds true is no longer a curiosity; it is a liability that lands on someone. Our reading is that much of today's safety rests on identity-as-authority — defining what a model is, and may claim, through instruction at inference time. We hold that this foundation is sand: under adversarial pressure it can leak, over-reject, and accumulate patch upon patch without ever reaching ground. The alternative we argue for is structural honesty — the requirements a statement must satisfy to be capable of being true at all, not a moral code laid on top. We do not claim to have the answer. We offer a structural, openly published, falsifiable account of why the current approach has a ceiling, and we invite the field to break it.",
                es: "A medida que los modelos se vuelven más capaces y alcanzan decisiones médicas, financieras y legales, el costo de la ficción con forma de hecho crece con ellos. Una respuesta segura que solo suena verdadera ya no es una curiosidad; es un riesgo que recae sobre alguien. Nuestra lectura es que gran parte de la seguridad actual se apoya en la identidad-como-autoridad — definir qué es un modelo, y qué puede afirmar, mediante instrucción en tiempo de inferencia. Sostenemos que ese cimiento es arena: bajo presión adversaria puede filtrarse, sobre-rechazar y acumular parche sobre parche sin llegar nunca a suelo firme. La alternativa que defendemos es la honestidad estructural — los requisitos que un enunciado debe satisfacer para ser capaz de ser verdadero, no un código moral puesto encima. No afirmamos tener la respuesta. Ofrecemos un relato estructural, publicado abiertamente y falsable, de por qué el enfoque actual tiene un techo, e invitamos al campo a refutarlo." },
      },
    },
    labels: {
      verifiedFact: { en: 'Verified result', es: 'Resultado verificado' },
      labsReading: { en: "The lab's reading", es: 'La lectura del lab' },
      research: { en: 'Research', es: 'Investigación' },
      approach: { en: 'The approach', es: 'El enfoque' },
      executionRules: { en: 'Execution rules', es: 'Reglas de ejecución' },
      availability: { en: 'Availability', es: 'Disponibilidad' },
    },
    ui: {
      publications: { en: 'Publications', es: 'Publicaciones' },
      ecclesiaHeading: { en: 'The Ecclesia', es: 'La Ecclesia' },
      ecclesiaBody: { en: '{entries} entries across {domains} thematic domains, plus a BUILDERS collection of {builders} profiles.',
                      es: '{entries} entradas en {domains} dominios temáticos, más una colección BUILDERS de {builders} perfiles.' },
      benchmarkHeading: { en: 'Benchmark & models', es: 'Benchmark y modelos' },
      benchmarkBody: { en: '{cases} test cases across {categories} categories. Fine-tuned models across {families}:',
                       es: '{cases} casos de prueba en {categories} categorías. Modelos ajustados en {families}:' },
      crossFamilyHeading: { en: 'Cross-family evidence', es: 'Evidencia entre familias' },
      crossFamilyLead: { en: 'Publicly-reproducible families — {families} — reach {metric}.',
                         es: 'Familias reproducibles públicamente — {families} — alcanzan {metric}.' },
      scaleFloorLabel: { en: 'Scale floor', es: 'Piso de escala' },
      exceptionLabel: { en: 'Documented exception', es: 'Excepción documentada' },
      operationalTestLabel: { en: 'The operational test:', es: 'La prueba operativa:' },
      operationalTest: { en: 'Will the response produce fact-shaped fiction?',
                         es: '¿Producirá la respuesta ficción con forma de hecho?' },
    },
  },
  held: ['gradient selectivity', 'Nothing is gated', '100% Open Source', 'six families', 'non-fabrication above 92'],
  links: [
    'https://doi.org/10.5281/zenodo.19634358',
    'https://doi.org/10.5281/zenodo.18644321',
    'https://doi.org/10.5281/zenodo.20056443',
    'https://github.com/lumensyntax-org/ecclesia',
    'https://huggingface.co/LumenSyntax',
    'https://github.com/lumensyntax-org',
    'https://github.com/lumensyntax-org/instrument-trap-benchmark',
    'https://huggingface.co/datasets/LumenSyntax/instrument-trap-benchmark',
    'https://huggingface.co/datasets/LumenSyntax/epistemic-probe-topic-balanced',
  ],
};
